name: route_CI
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 18 * * 1'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要推送代码时
      actions: read    # 其他必要权限
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      # - run: pip install requests
      - run: |
          python produce.py
          ls -la

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # 添加所有新文件/修改（可根据路径调整）
          git add .

          # 检查是否有变更需要提交
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated commit: Add generated files"
            git push origin main
            echo "Changes pushed."
          else
            echo "No changes to commit."
          fi
